# TD Numpy côté Matrix

## Exercice 1: Manipulations de base

### 1.1

In [2]:
import numpy as np
A = np.arange(0, 100, 3)
print(A)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


### 1.2

In [3]:
B = np.sin(A**2 * np.pi /2)
print(B)

[ 0.00000000e+00  1.00000000e+00 -2.20436424e-15  1.00000000e+00
 -8.81745695e-15  1.00000000e+00 -4.11555602e-14  1.00000000e+00
 -3.52698278e-14  1.00000000e+00 -7.64253880e-14  1.00000000e+00
 -1.64622241e-13  1.00000000e+00 -1.86173549e-13  1.00000000e+00
 -1.41079311e-13  1.00000000e+00 -4.84086880e-13  1.00000000e+00
 -3.05701552e-13  1.00000000e+00 -6.06706795e-14  1.00000000e+00
 -6.58488964e-13  1.00000000e+00 -1.18966170e-12  1.00000000e+00
 -7.44694194e-13  1.00000000e+00 -1.14257584e-12  1.00000000e+00
 -5.64317245e-13  1.00000000e+00]


### 1.3

In [4]:
C = B.max()
print(C)

1.0


### 1.4

In [14]:
D = len (np.argwhere(B==B.max()))
D

17

## Exercice 2 

### 2.1

In [3]:
import numpy as np
A = [[6, 0, 0, 0], [0, 6, 0, 0], [0, 0, 6, 0], [0, 0, 0, 8]]
print(A)
B = np.triu(A)
B
C = np.tril(B)
C
D = (A==C).all()
D

[[6, 0, 0, 0], [0, 6, 0, 0], [0, 0, 6, 0], [0, 0, 0, 8]]


True

### 2.2

In [9]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print (M)
N = M
print(N)
Z = np.triu (N)
print(Z)
Y = (M==Z).all()
print(Y)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
False


## Exercice 3

### Méthode 1

In [55]:
import numpy as np
A = np.zeros((7, 6))

B = np.ones((1, 6))

C = np.concatenate((A, B), axis = 0)

D = np.ones((8, 1))

E = np.concatenate((C, D), axis=1)

F = np.concatenate((D, E), axis=1)
print(F)

[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


### Méthode 2

In [54]:
A= np.zeros((7, 6))
A= np.pad(A,(0,1), mode='constant', constant_values = 1)
A[0::,0] = 1
print (A)

[[1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### Méthode 3

In [40]:
A = np.zeros((8, 8))
for i in range (8) :
    A[ i ,0]=1
    A[ i ,7]=1
    A[7 , i ]=1
print (A)

[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


## Exercice 4

### 4.1

In [41]:
n = 1000000
i = 0
somme = 0
for i in range (n):
    somme = somme + i
print(somme)
    

499999500000


### 4.2

In [67]:
import time
t = time.time()
n = 1000000
i = 0
somme = 0
for i in range (n):
    somme = somme + i
print(somme)
print(time.time() - t)

499999500000
0.09376811981201172


### 4.3

In [39]:
n = 1000000
somme = np.sum(np.arange(0, n))
print(somme)

1783293664


### 4.4

In [68]:
t= time.perf_counter()
n = 1000000
somme = np.sum(np.arange(0, n))
print(somme)
print(time.perf_counter()-t)

1783293664
0.005070915000032983


La somme faite sans numpy est plus lente mais juste.
La somme avec numpy a des limites en effet elle s'arrête avant d'avoir fini. Donc la méthode avec numpy est moins fiable.

## Exercice 5

### 5.1

In [32]:
a = np.random.randint(50,size=(50,50))
print (a)

[[13 35 17 ... 33 48 19]
 [20  6 24 ... 38 10  9]
 [ 9  6 36 ... 40 10 46]
 ...
 [12  0 42 ... 34  3  8]
 [14  4 35 ... 26 44 49]
 [ 8 37  0 ... 19  1  3]]


### 5.2

In [38]:
max = 0
somme = 0
for i in range (50):
    for j in range (i):
        somme = a[i, j+1]- a[i, j]
        if somme > max:
            max = somme
print(max)

47


## Exercice 6

### 6.1

In [63]:
A= np.random.rand(50,50)           
print(A)

[[0.83698204 0.42470323 0.16395178 ... 0.08648093 0.55389463 0.18420131]
 [0.57393356 0.68563267 0.76618485 ... 0.68470153 0.44194025 0.2770524 ]
 [0.52004005 0.06617132 0.00187282 ... 0.32887831 0.41240279 0.72146994]
 ...
 [0.69721159 0.99115046 0.5345504  ... 0.16776992 0.00626812 0.112811  ]
 [0.32033956 0.01123376 0.8016658  ... 0.73170239 0.85849807 0.96065535]
 [0.29783316 0.78178729 0.91385294 ... 0.02967944 0.39640209 0.71497699]]


### 6.2

In [65]:
B =len (np.argwhere(A <0.5))
print(B)

1284


### 6.3

In [66]:
A[A<0.5]=0
A[A>0.5]=1
print (A)

[[1. 0. 0. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 1. 1. ... 0. 0. 1.]]


## Exercice 7

### 7.1

### 7.2

In [72]:
a= np.array([[1, 2, 1, 1], [0, 1, 2, 1], [1, 0, 1, 2], [2, 1, 0, 1]])
b = np.array([[0], [0], [1], [0]])
c = np.linalg.solve(a, b)
print (c)

[[-0.5]
 [ 0. ]
 [-0.5]
 [ 1. ]]


### 7.3